# -*- coding: utf-8 -*-
"""citra_digital_23424040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilG_iZH0HBQuTWVYzTOiHSGJWxX4EOr7
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Ambil nama file
filename = list(uploaded.keys())[0]

# Baca gambar
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.title("Gambar Asli")
plt.axis('off')

brightness = 50  # tambah nilai kecerahan

bright_img = cv2.convertScaleAbs(img, alpha=1, beta=brightness)

plt.imshow(bright_img)
plt.title("Brightness Image")
plt.axis('off')

alpha = 1.5  # kontras (>1 lebih kontras)

contrast_img = cv2.convertScaleAbs(img, alpha=alpha, beta=0)

plt.imshow(contrast_img)
plt.title("Contrast Image")
plt.axis('off')

gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(gray, cmap='gray')
plt.title("Grayscale")
plt.axis('off')

plt.subplot(1,2,2)
plt.hist(gray.ravel(), bins=256, range=[0,256])
plt.title("Histogram")
plt.show()

equalized = cv2.equalizeHist(gray)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(gray, cmap='gray')
plt.title("Before")

plt.subplot(1,2,2)
plt.imshow(equalized, cmap='gray')
plt.title("After Equalization")

plt.show()

# Grayscale
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

# Histogram Equalization
enhanced = cv2.equalizeHist(gray)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(gray, cmap='gray')
plt.title("Grayscale")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(enhanced, cmap='gray')
plt.title("Enhanced")
plt.axis('off')

plt.show()